model:
  num_classes_task_a: 3        # Number of classes for Task A (e.g., classification)
  num_labels_task_b: 4         # Number of labels for Task B (e.g., NER)
  freeze_backbone: true        # Freeze the BERT backbone (true/false)

training:
  learning_rate: 2e-5          # Learning rate for the optimizer
  num_epochs: 10               # Number of training epochs
  batch_size: 2                # Batch size for DataLoader
  task: both                   # Which task(s) to train: 'task_a', 'task_b', or 'both'

device: cuda                   # Device to use: 'cuda' or 'cpu'